name: ouisync_plugin
description: A flutter plugin providing high-level dart API for the ouisync native library
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  path: ^1.8.0
  platform: ^3.1.0

dev_dependencies:
  ffigen: ^4.1.2
  lints: ^1.0.1
  test: ^1.17.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: ie.equalit.ouisync_plugin
        pluginClass: OuisyncPlugin
      ios:
        pluginClass: OuisyncPlugin
      windows:
        pluginClass: OuisyncPlugin

ffigen:
  name: 'Bindings'
  description: 'Bindings to the ouisync library'
  output: 'lib/bindings.dart'
  headers:
    entry-points:
      - './ouisync/target/bindings.h'
    include-directives:
      - '**bindings.h'

